# imports

In [6]:
import numpy as np

# LLN의 확장 -- 정상분포 관련내용

`-` 유일한 정상분포를 가진다는 것을 알고 있다고 하자. 이를 쉽고 편하게 구하는 방법? 

`-` **정리(큰 수의 법칙)**: 확률변수열 $\{X_t\}_{t \in \mathbb{N}_0}$ 이 서로 독립이고 동일한 분포를 가진다고 하자. 또한 $\mathbb{E}[|X_0|]<\infty$ 이라고 가정하자. 그러면 아래가 성립한다. 

$$\lim_{T\to\infty} \frac{1}{T}\sum_{t=0}^{T-1}X_t = \mathbb{E}_{\pi}[X_0]$$

단, 여기에서 $\pi$는 $X_0$의 분포이다. 

`-` **Thm** (에르고딕정리): 확률변수열 $\{X_t\}_{t \in \mathbb{N}_0}$이 finite and irreducible HMC 라고 하자. 그러면 임의의 함수 $f:S \to \mathbb{R}$에 대하여 아래가 성립한다. 

$$\lim_{T\to\infty} \frac{1}{T}\sum_{t=0}^{T-1}f(X_t) = \mathbb{E}_{\boldsymbol \pi}[f(X_0)]$$

여기에서 $\boldsymbol \pi$는 ${\boldsymbol \pi}^\top = {\boldsymbol \pi}^\top{\bf P}$를 만족하는 **유일한** 정상분포이고 ${\bf P}$는 $\{X_t\}$의 transition matrix 이다.

`-` 만약에 $$f(i)= \begin{cases} 1 & i = 0 \\ 0 & i=1\end{cases}$$ 이라고 하자. 그러면 위의 이론은 아래와 같이 변경된다. 

$$\lim_{T\to\infty} \frac{1}{T}\sum_{t=0}^{T-1}I(X_t=0) =\mathbb{E}_{\pi}[I(X_0=0)] = \mathbb{P}_{\pi}[X_0=0]=\pi_0$$

> 이 이론의 의미: 

## 예제1: 단위행렬 

HMC $\{X_t\}$의 전이행렬이 아래와 같다고 하자. 

In [8]:
P = np.array([[1,0],[0,1]])
P

array([[1, 0],
       [0, 1]])

$\{X_t\}$는 유일한 정상분포를 가지는가? 가진다면 시간평균을 이용하여 정상분포를 근사하라.

(풀이)

## 예제2: 순환이동 

HMC $\{X_t\}$의 전이행렬이 아래와 같다고 하자. 

In [10]:
P = np.array([[0,1],[1,0]])
P

array([[0, 1],
       [1, 0]])

$\{X_t\}$는 유일한 정상분포를 가지는가? 가진다면 시간평균을 이용하여 정상분포를 구하여라. 

(풀이)

$\{X_t\}$는 finite and irreducible HMC 이므로 유일한 정상분포를 가진다. 따라서 

- $\big(\frac{1}{T}\sum_{t=0}^{T-1}I(X_t=0),\frac{1}{T}\sum_{t=0}^{T-1}I(X_t=1)\big)=(\hat{\pi}_0,\hat{\pi}_1)\approx (1/2,1/2)$

와 같이 구할 수 있음 

## 예제3: 비가 온다, 안온다 

HMC $\{X_t\}$의 전이행렬이 아래와 같다고 하자. 

In [23]:
P = np.array([[0.4,0.6],
              [0.7,0.3]])
P

array([[0.4, 0.6],
       [0.7, 0.3]])

$\{X_t\}$는 유일한 정상분포를 가지는가? 가진다면 시간평균을 이용하여 정상분포를 구하여라. 

(풀이) 이 강의노트의 [풀이4](https://guebin.github.io/SP2023/posts/2.%20마코프체인/2023-04-13-7wk-1.html)

# 정상분포가 존재하지 않는 경우 

## 예제: 오른쪽으로만 갈래

아래와 같은 transition matrix ${\bf P}$를 고려하자. 

$${\bf P} = \begin{bmatrix} 
0 & 1 & 0 & 0 & 0 & \dots \\ 
0 & 0 & 1 & 0 & 0 & \dots \\ 
0 & 0 & 0 & 1 & 0 & \dots \\ 
0 & 0 & 0 & 0 & 1 & \dots \\ 
\dots & \dots & \dots & \dots & \dots & \dots 
\end{bmatrix}$$

정상분포 ${\boldsymbol \pi}^\top=[\pi_0,\pi_1,\pi_2,\dots]$ 가 존재하기 위해서는 아래가 성립해야 한다. 

- $\pi_0=\pi_1$ 
- $\pi_1=\pi_2$ 
- $\pi_1=\pi_2$ 
- $\dots$

즉 모든 $n \in \mathbb{N}_0$에 대하여 $\pi_0=\pi_n$이 성립해아한다. 그런데 그럴 수 없다. 

# 정리

$\{X_t\}$는 HMC 라고 하자. 

|CaseNO|대표예제|FINITE|IRR(연결)|AP(비주기)|${\bf P}$의 수렴|동일한 row|정상분포존재|정상분포유일|에르고딕정리를 만족|에르고딕|
|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
|1||O|X|X| X|X|O|X|X|X
|2|단위행렬|O|X|O| O|X|O|X|X|X|
|3|순환이동|O|O|X| X|X|O|O|O|X|
|4|나이스|O|O|O| O|O|O|O|O|O|