## PR, NR, TR

`-` 기호정의:

`-` **가짜정의**: $\{X_t\}$가 상태공간 $E$에서 정의된 HMC 라고 하자. 상태 $i$에 대한 ***return time*** $T_i$는 마을 $i$에 있던 나그네가 다시 마을 $i$로 돌아오는 시간이라고 하자. 

> 나그네는 마을을 랜덤으로 이동하므로 $T_i$는 랜덤변수가 된다. 즉 $E(T_i)$를 고려할 수 있다는 의미 

`-` **정의**: $\{X_t\}$가 상태공간 $E$에서 정의된 HMC 라고 하자. $T_i$를 상태 $i \in E$에 대한 ***return time*** 이라고 하자. 만약에 상태 $i \in E$ 가 아래의 식을 만족한다면

$$\mathbb{P}_i(T_i<\infty)=1$$

$i$는 recurrent 하다고 표현하고, 그렇지 않으면 $i$는 transient 하다고 표현한다. 만약에 recurrent state $i$가 아래식을 만족한다면 

$$\mathbb{E}_i[T_i] < \infty$$ 

state $i$를 positive recurrent 라고 하고 그렇지 않으면 null recurrent 라고 한다. 

`-` **이론**: HMC $\{X_t\}$가 IRR 이라면 모든 $i$는 같은 ***nature*** 를 가진다. 즉 $\{X_t\}$가 IRR 이면 아래중의 하나이다. 

1. 모든 상태가 transient 하다. 
2. 모든 상태가 null recurrent 하다. 
3. 모든 상태가 positive recurrent 하다. 

`-` **정의:** HMC $\{X_t\}$가 (1) IRR (2) PR (3) AP 조건을 만족한다면 $\{X_t\}$를 에르고딕 마코프체인이라고 부른다. 

`-` Overview 

- 결국 우리가 FINITE 인 경우 얻어냈던 나이스케이스는 (1) IRR (2) PR (3) AP 조건이다. 
- IRR은 있으나 마나 한 조건이라서 사실상 (2) PR 과 (3) AP 를 만족하면된다. 
- AP가 만족하는 경우는 극한분포가 유일하게 존재한다. (극한분포는 정의상 유일함) 
- PR이 성립하는 경우는 정상분포가 유일하게 존재한다. 그리고 에르고딕 정리가 성립한다. 

# aperiodic 

## 예제3: 8wk-1, 예시3 

EX: $\{X_t\}$를 아래와 같은 transition matrix를 가지는 HMC라고 하자.

In [ ]:
P = np.array([[1.0, 0.0],
              [0.05,0.95]])
P

array([[1.  , 0.  ],
       [0.05, 0.95]])

`-` 관찰1: 상태0으로 결국 가게 되어있다. 

`-` 관찰2: 상태1에는 일시적으로 머문다. 상태0에는 반복적으로 방문한다. 

`-` 주기??

- 상태0의 주기는 1이라고 할 수 있다. 
- 상태1의 주기는? 무한대? 

`-` 이 마코프체인은 AP인가? 

- 질문이 틀림. 
- 주기라는 개념은 recurrent state인 경우에만 정의한다. 

## AP의 정의 

`-` **정의**: $\{X_t\}$가 상태공간 $E$에서 정의된 HMC 라고 하자. Recurrnet state $i \in E$ 에 대하여 아래와 같은 집합 $I_i$ 를 생각하자. 

$$I_i = \{t: p_{ii}^{(t)}>0,~t \geq 1 \}$$

그렇다면 $i$의 주기는 $I_i$의 모든 원소들의 최대공약수로 정의한다. 

`-` **이론**: $\{X_t\}$가 상태공간 $E$에서 정의된 HMC 라고 하자. $\{X_t\}$가 IRR & recurrent 라고 가정하자. 그러면 모든 상태는 같은 주기를 가진다. 

`-` 예시1: 아래와 같은 전이확률을 고려하자. 

In [ ]:
P = np.array([0.0, 1.0, 0.0,
              0.0, 0.0, 1.0,
              1.0, 0.0, 0.0]).reshape(3,3)
P

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

```{mermaid}
flowchart LR
  0 -->|1| 1
  1 -->|1| 2
  2 -->|1| 0
```

모든 상태 $i$에 대하여 주기를 구하라. 

(해설) 

### 예제2 

`-` 아래와 같은 전이확률을 고려하자. 

In [ ]:
P = np.array([0.0, 1.0, 0.0, 0.0,
              0.0, 0.0, 0.0, 1.0,
              0.0, 1.0, 0.0, 0.0,
              1/3, 0.0, 2/3, 0.0]).reshape(4,4)
P

array([[0.        , 1.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        ],
       [0.        , 1.        , 0.        , 0.        ],
       [0.33333333, 0.        , 0.66666667, 0.        ]])

```{mermaid}
flowchart LR
  0 -->|1| 1
  1 -->|1| 3
  2 -->|1| 1
  3 -->|1/3| 0 
  3 -->|2/3| 2
```

모든 상태 $i$에 대하여 주기를 구하라. 

(해설) 